version: '2'
services:
  broker-1:
    image: confluentinc/cp-kafka:4.0.0
    container_name: broker-1
    extra_hosts:
      - "zookeeper_1:192.168.16.10"
      - "zookeeper_2:192.168.16.20"
      - "zookeeper_3:192.168.16.30"
    env_file:
      - ./kafka-broker-1.env
    ports:
      - 19092:19092
      - 9092:9092
    volumes:
      - /home/ubuntu/kafka/broker_1/data:/var/lib/kafka/data

